# Does this project really need a Docker compose file?
# Not currently. But I'm too lazy to actually write the proper docker run syntax so whatever
version: "3.8"
services:
  bot:
    read_only: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app/cbt:/cbt
      - ./config.yaml:/config/config.yaml
    command: ["python3", "main.py"]
    depends_on:
      minio:
        condition: service_healthy
      createbuckets:
        condition: service_completed_successfully
  minio:
    ports:
        - "9000:9000"
        - "9001:9001"
    container_name: minio
    env_file:
      - .env
    volumes:
        - minio_data:/data
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    healthcheck:
      test: curl --fail -s http://127.0.0.1:9001 || exit 1
      interval: 10s
      timeout: 1s
      retries: 2 
      start_period: 1s
      start_interval: 1s

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 admin bigadminpassword;
      /usr/bin/mc mb myminio/somebucketname;
      /usr/bin/mc policy set public myminio/somebucketname;
      exit 0;
      "


volumes:
  minio_data: